  const stepData = [
    {
      stepName:'定期点检流程1',
      auditName:'张良1',
      stepTime:'点检前',
      stepContent:'啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊',
      stepPiont:'点检前',
      stepId:1
  },
  {
    stepName:'定期点检流程2',
    auditName:'张良2',
    stepTime:'点检前',
    stepContent:'啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊',
    stepPiont:'点检前',
    stepId:2
  },
  {
    stepName:'定期点检流程3',
    auditName:'张良3',
    stepTime:'点检前',
    stepContent:'啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊',
    stepPiont:'点检前',
    stepId:3
  },
  {
    stepName:'定期点检流程4',
    auditName:'张良4',
    stepTime:'点检前',
    stepContent:'啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊',
    stepPiont:'点检前',
    stepId:4
  },      
  {
    stepName:'定期点检流程5',
    auditName:'张良5',
    stepTime:'点检前',
    stepContent:'啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊',
    stepPiont:'点检前',
    stepId:5
  },
]

export default  stepData;