export default {
  namespace: 'jfjh',

  state: {
    before: [
      {
        id: '1',
        period: '尖',
        consumeBeforeAdjustment: 543.23,
        adjustOrNot: false,
        consumeValue: 50,
        periodAfterAdjustment: '谷',
      },
      {
        id: '2',
        period: '峰',
        consumeBeforeAdjustment: 600.42,
        adjustOrNot: true,
        consumeValue: 50,
        periodAfterAdjustment: '谷',
      },
      {
        id: '3',
        period: '平',
        consumeBeforeAdjustment: 1351.23,
        adjustOrNot: false,
        consumeValue: 50,
        periodAfterAdjustment: '谷',
      },
      {
        id: '4',
        period: '谷',
        consumeBeforeAdjustment: 770.34,
        adjustOrNot: false,
        consumeValue: 50,
        periodAfterAdjustment: '谷',
      },
    ],
    after: [
      {
        id: '1',
        period: '尖',
        price: 54.23,
        consumeBeforeAdjustment: 543.23,
        costBeforAdjustment: 5423,
        consumeAfterAdjustment: 443.23,
        costAfterAdjustment: 4423,
      },
      {
        id: '2',
        period: '峰',
        price: 60.42,
        consumeBeforeAdjustment: 600.42,
        costBeforAdjustment: 6042,
        consumeAfterAdjustment: 500.42,
        costAfterAdjustment: 5042,
      },
      {
        id: '3',
        period: '平',
        price: 131.23,
        consumeBeforeAdjustment: 1351.23,
        costBeforAdjustment: 13123,
        consumeAfterAdjustment: 951.23,
        costAfterAdjustment: 12123,
      },
      {
        id: '4',
        period: '谷',
        price: 77.34,
        consumeBeforeAdjustment: 770.34,
        costBeforAdjustment: 7734,
        consumeAfterAdjustment: 670.34,
        costAfterAdjustment: 6734,
      },
    ],
  },
  effects: {},
  reducers: {},
};
